/*
 * Copyright (c) 2026, Brettgod1355 <github.com/Brettgod1355>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.slayercompanion.data;

import com.google.gson.Gson;
import com.slayercompanion.task.SlayerMaster;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;
import javax.inject.Inject;
import javax.inject.Singleton;
import lombok.extern.slf4j.Slf4j;

/**
 * Loads the bundled reference data shipped inside the plugin jar. The files are generated by the
 * maintainer from the OSRS Wiki with tools/datagen; the plugin never fetches anything at runtime.
 * <p>
 * Loading reads classpath resources only (no file system access). Safe to call from any thread;
 * the first call parses lazily.
 */
@Slf4j
@Singleton
public class SlayerData
{
	private static final String BASE = "/com/slayercompanion/data/";

	private final Gson gson;

	private volatile MastersFile masters;
	private volatile List<TaskInfo> tasks;
	private volatile UnlocksFile unlocks;
	private volatile WildernessInfo wilderness;
	private volatile AreaRules areaRules;

	@Inject
	SlayerData(Gson gson)
	{
		this.gson = gson;
	}

	public List<MasterInfo> masters()
	{
		MastersFile f = mastersFile();
		return f == null || f.getMasters() == null ? Collections.emptyList() : f.getMasters();
	}

	public Optional<MasterInfo> master(@Nullable SlayerMaster master)
	{
		if (master == null)
		{
			return Optional.empty();
		}
		for (MasterInfo m : masters())
		{
			if (master.getDataId().equalsIgnoreCase(m.getId()))
			{
				return Optional.of(m);
			}
		}
		return Optional.empty();
	}

	public String rule(String key)
	{
		MastersFile f = mastersFile();
		if (f == null || f.getRules() == null)
		{
			return "";
		}
		return f.getRules().getOrDefault(key, "");
	}

	/** All bundled tasks. */
	public List<TaskInfo> tasks()
	{
		if (tasks == null)
		{
			synchronized (this)
			{
				if (tasks == null)
				{
					TaskInfo[] arr = load("tasks.json", TaskInfo[].class);
					tasks = arr == null ? Collections.emptyList() : Collections.unmodifiableList(java.util.Arrays.asList(arr));
				}
			}
		}
		return tasks;
	}

	/** Look a task up by its game display name; also matches boss/alternative names. */
	public Optional<TaskInfo> task(@Nullable String name)
	{
		if (name == null || name.isEmpty())
		{
			return Optional.empty();
		}
		String wanted = normalise(name);
		for (TaskInfo t : tasks())
		{
			if (normalise(t.getTask()).equals(wanted))
			{
				return Optional.of(t);
			}
		}
		for (TaskInfo t : tasks())
		{
			for (String alt : t.alternativesOrEmpty())
			{
				if (normalise(alt).equals(wanted))
				{
					return Optional.of(t);
				}
			}
		}
		return Optional.empty();
	}

	public List<UnlockInfo> unlocks()
	{
		if (unlocks == null)
		{
			synchronized (this)
			{
				if (unlocks == null)
				{
					UnlocksFile f = load("unlocks.json", UnlocksFile.class);
					unlocks = f == null ? new UnlocksFile() : f;
				}
			}
		}
		return unlocks.getUnlocks() == null ? Collections.emptyList() : unlocks.getUnlocks();
	}

	public WildernessInfo wilderness()
	{
		if (wilderness == null)
		{
			synchronized (this)
			{
				if (wilderness == null)
				{
					WildernessInfo w = load("wilderness.json", WildernessInfo.class);
					wilderness = w == null ? new WildernessInfo() : w;
				}
			}
		}
		return wilderness;
	}

	public AreaRules areaRules()
	{
		if (areaRules == null)
		{
			synchronized (this)
			{
				if (areaRules == null)
				{
					AreaRules a = load("area-rules.json", AreaRules.class);
					areaRules = a == null ? new AreaRules() : a;
				}
			}
		}
		return areaRules;
	}

	public static String normalise(String s)
	{
		String n = s.toLowerCase().trim();
		if (n.startsWith("the "))
		{
			n = n.substring(4);
		}
		return n.replaceAll("[^a-z0-9]", "");
	}

	@Nullable
	private MastersFile mastersFile()
	{
		if (masters == null)
		{
			synchronized (this)
			{
				if (masters == null)
				{
					masters = load("masters.json", MastersFile.class);
				}
			}
		}
		return masters;
	}

	@Nullable
	<T> T load(String file, Class<T> type)
	{
		try (InputStream in = SlayerData.class.getResourceAsStream(BASE + file))
		{
			if (in == null)
			{
				log.warn("Bundled data file missing: {}", file);
				return null;
			}
			try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8))
			{
				return gson.fromJson(reader, type);
			}
		}
		catch (Exception e)
		{
			log.warn("Could not read bundled data file {}", file, e);
			return null;
		}
	}
}
